
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mycompany.aplicacioncliente.main.analizadoresconsultas;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PAGINAS_POPULARES = 5;
  public static final int IMAGEN = 14;
  public static final int PUNTO = 9;
  public static final int PALABRA = 17;
  public static final int CONSULTAR = 2;
  public static final int TODOS = 11;
  public static final int VIDEO = 15;
  public static final int MENU = 16;
  public static final int COMPONENTE = 6;
  public static final int COMA = 8;
  public static final int PARRAFO = 13;
  public static final int EOF = 0;
  public static final int COMILLA = 7;
  public static final int VISITAS_PAGINA = 4;
  public static final int error = 1;
  public static final int VISITAS_SITIO = 3;
  public static final int TITULO = 12;
  public static final int PUNTO_Y_COMA = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CONSULTAR",
  "VISITAS_SITIO",
  "VISITAS_PAGINA",
  "PAGINAS_POPULARES",
  "COMPONENTE",
  "COMILLA",
  "COMA",
  "PUNTO",
  "PUNTO_Y_COMA",
  "TODOS",
  "TITULO",
  "PARRAFO",
  "IMAGEN",
  "VIDEO",
  "MENU",
  "PALABRA"
  };
}

