
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mycompany.aplicacioncliente.main.analizadoresxml;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int USUARIO_M = 17;
  public static final int NUMERO = 56;
  public static final int BORRAR_PAGINA = 5;
  public static final int ALINEACION = 33;
  public static final int PAGINA = 18;
  public static final int PARAMETROS = 22;
  public static final int NOMBRE = 41;
  public static final int USUARIO_C = 14;
  public static final int CORCHETE_I = 48;
  public static final int ANCHO = 40;
  public static final int CORCHETE_D = 49;
  public static final int IZQUIERDA = 34;
  public static final int VIDEO = 30;
  public static final int ETIQUETAS = 26;
  public static final int BORRAR_SITIO = 4;
  public static final int FECHA = 53;
  public static final int MENU = 31;
  public static final int IGUAL = 50;
  public static final int CENTRAR = 35;
  public static final int TITULO = 11;
  public static final int PADRE = 13;
  public static final int ID = 10;
  public static final int NUEVA_PAGINA = 3;
  public static final int EOF = 0;
  public static final int BORRAR_COMPONENTE = 8;
  public static final int PALABRA = 51;
  public static final int CLASE = 19;
  public static final int COMILLA = 43;
  public static final int error = 1;
  public static final int MENOR_DIAGONAL = 45;
  public static final int MENOR = 44;
  public static final int URL = 52;
  public static final int ATRIBUTOS = 24;
  public static final int ATRIBUTO = 25;
  public static final int ACCION = 21;
  public static final int COLOR = 37;
  public static final int FECHA_M = 16;
  public static final int MAYOR = 46;
  public static final int MAYOR_DIAGONAL = 47;
  public static final int VALOR = 42;
  public static final int DERECHA = 36;
  public static final int IMAGEN = 29;
  public static final int ORIGEN = 38;
  public static final int PARRAFO = 28;
  public static final int MODIFICAR_COMPONENTE = 9;
  public static final int FECHA_C = 15;
  public static final int NUMERO_COLOR = 54;
  public static final int AGREGAR_COMPONENTE = 7;
  public static final int PARAMETRO = 23;
  public static final int ACCIONES = 20;
  public static final int SITIO = 12;
  public static final int TEXTO = 32;
  public static final int ETIQUETA = 27;
  public static final int ALTURA = 39;
  public static final int NUEVO_SITIO = 2;
  public static final int CONTENIDO = 55;
  public static final int MODIFICAR_PAGINA = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUEVO_SITIO",
  "NUEVA_PAGINA",
  "BORRAR_SITIO",
  "BORRAR_PAGINA",
  "MODIFICAR_PAGINA",
  "AGREGAR_COMPONENTE",
  "BORRAR_COMPONENTE",
  "MODIFICAR_COMPONENTE",
  "ID",
  "TITULO",
  "SITIO",
  "PADRE",
  "USUARIO_C",
  "FECHA_C",
  "FECHA_M",
  "USUARIO_M",
  "PAGINA",
  "CLASE",
  "ACCIONES",
  "ACCION",
  "PARAMETROS",
  "PARAMETRO",
  "ATRIBUTOS",
  "ATRIBUTO",
  "ETIQUETAS",
  "ETIQUETA",
  "PARRAFO",
  "IMAGEN",
  "VIDEO",
  "MENU",
  "TEXTO",
  "ALINEACION",
  "IZQUIERDA",
  "CENTRAR",
  "DERECHA",
  "COLOR",
  "ORIGEN",
  "ALTURA",
  "ANCHO",
  "NOMBRE",
  "VALOR",
  "COMILLA",
  "MENOR",
  "MENOR_DIAGONAL",
  "MAYOR",
  "MAYOR_DIAGONAL",
  "CORCHETE_I",
  "CORCHETE_D",
  "IGUAL",
  "PALABRA",
  "URL",
  "FECHA",
  "NUMERO_COLOR",
  "CONTENIDO",
  "NUMERO"
  };
}

